[tool.poetry]
name = "rts"
version = "0.1.0"
description = ""
authors = ["Kirell Benzi <kirell.benzi@epfl.ch>"]

[tool.poetry.dependencies]
python = "^3.8"
jupyterlab = "^3.5.1"
elasticsearch = "^8.5.2"
numpy = "^1.23.5"
meilisearch = "^0.23.0"
pandas = "^1.5.2"
orjson = "^3.8.3"
whisper = {git = "https://github.com/openai/whisper.git", rev = "main"}
torch = "^1.13.0"
torchvision = "^0.14.0"
torchaudio = "^0.13.0"
tqdm = "^4.64.1"
more-itertools = "^9.0.0"
ffmpeg-python = "^0.2.0"
transformers = "^4.25.1"
tables = "^3.7.0"
matplotlib = "^3.6.2"
av = "^10.0.0"

[tool.poetry.dev-dependencies]
poethepoet = "^0.16.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
