[tool.poetry]
name = "rts"
version = "0.1.0"
description = ""
authors = ["Kirell Benzi <kirell.benzi@epfl.ch>"]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
jupyterlab = "^3.5.1"
numpy = "^1.23.5"
meilisearch = "^0.23.0"
pandas = "^1.5.2"
orjson = "^3.8.3"
openai-whisper = {git = "https://github.com/openai/whisper.git", rev = "main"}
torch = "^1.13.0"
torchvision = "^0.14.0"
torchaudio = "^0.13.0"
tqdm = "^4.64.1"
more-itertools = "^9.0.0"
ffmpeg-python = "^0.2.0"
transformers = "^4.25.1"
tables = "^3.7.0"
matplotlib = "^3.6.2"
av = "^10.0.0"
scenedetect = {extras = ["opencv-headless"], version = "^0.6.1"}
cupy-cuda12x = "^11.5.0"
spacy = {extras = ["cuda-12"], version = "^3.5.0"}
geonamescache = "^1.5.0"
click = "^8.1.3"
weaviate-client = "^3.11.0"
pillow = "^9.4.0"

[tool.poetry.dev-dependencies]
poethepoet = "^0.18.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
install-spacy-models = "python -m spacy download fr_core_news_lg"
start-weaviate = "docker compose -f docker/weaviate.yml up -d"
stop-weaviate = "docker compose -f docker/weaviate.yml down"
run-pipeline = "python -m rts.cli pipeline --compute-transcript"