apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5672           
    targetPort: 5672
    protocol: TCP
    name: amqp
    nodePort: 31672     
  - port: 15672         
    targetPort: 15672
    protocol: TCP
    name: management
    nodePort: 31673   
  selector:
    app: rabbitmq
