version: '3.8'

services:
  pose-detection:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: pose-openpifpaf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]