apiVersion: batch/v1
kind: Job
metadata:
  name: pose-openpifpaf
spec:
  completions: 8
  parallelism: 2
  template:
    metadata:
      name: pose-openpifpaf
    spec:
      containers:
      - name: c
        image: docker.io/arattinger/pose-openpifpaf
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: job1
      restartPolicy: OnFailure
