"""Clean Projection table

Revision ID: 83f4e38fabef
Revises: 14a91e8e2186
Create Date: 2024-04-30 15:34:45.222214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f4e38fabef'
down_revision = '14a91e8e2186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projection', schema=None) as batch_op:
        batch_op.drop_column('atlas_folder_path')
        batch_op.drop_column('atlas_width')
        batch_op.drop_column('tile_size')
        batch_op.drop_column('atlas_count')
        batch_op.drop_column('total_tiles')
        batch_op.drop_column('tiles_per_atlas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atlas_folder_path', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('atlas_width', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tile_size', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('atlas_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('total_tiles', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tiles_per_atlas', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###